### ISSUE TITLE
[Provisioning] There should be an easy way to recompile the Lisp binary

### ISSUE THREAD

**Issue by mathieulegrand** [cicakhq/potato#7]
Right now, `vagrant provision` is the only way to force a recompilation of the CL binary; but it also will run a full provisioning – which is slow and error prone when having poor network connectivity (aka downloading `solr` again is a pain).
It would be useful to have a simple way only to recompile the CL binary to accept a simple change on the server side.

**Comment by lokedhs** [comment]
What's wrong with git pull and build_binary.sh?

**Comment by mathieulegrand** [comment]
There is more to be done for the current deployed VM (see below). So it needs a wrapper to call `build_binary.sh` properly from the host (so that I don't have to `vagrant ssh`, `sudo -s -u potato`, go to the right directory and so on).

```
bash-4.2$ tools/build_binary.sh 
tools/build_binary.sh: line 7: sbcl: command not found
bash-4.2$ id
uid=1214(potato) gid=499(potato) groups=499(potato),500(sudo)
```

**Comment by lokedhs** [comment]
This issue is not applicable anymore.
