### ISSUE TITLE
Asset compilation chain is too complex

### ISSUE THREAD

**Issue by ddacunha** [cicakhq/potato#8]
Asset compilation chain is as follows:
### [Gulp](http://gulpjs.com)
- compiles [Less](http://lesscss.org) into CSS and copy them into place
- copy [fonts](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/web-app/src/fonts) into place.
- copy [MathJax](https://github.com/cicakhq/potato/blob/2fc12b9848237c8690e432180d275ceb8692c43c/web-app/src/html/mathjax.html) bootstrap into place.
- copy [images](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/web-app/src/images) into place.
- copy [JavaScript utilities](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/web-app/src/js) into place.
- copy FineUploader and FineUploader S3 JavaScript files into place.

Gulp also generate part of the [manifest](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/src/template/manifest) for the CSS files.
### [Bower](http://bower.io)

Downloads:
- [jQuery](https://jquery.com)
- [FontAwesome](http://fontawesome.io/?utm_source=hackernewsletter)
- [DataTables](https://datatables.net)
- [Dropit](http://www.dropitproject.com)
- [jQuery-contextMenu](http://swisnl.github.io/jQuery-contextMenu/index.html)
- [Moment.js](http://momentjs.com)
- [fontface-source-sans-pro](https://github.com/qorbani/fontface-source-sans-pro)
### [Leiningen](http://leiningen.org)

Compiles [ClojureScript](https://github.com/clojure/clojurescript) in [web-app/src/cljs](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/web-app/src/cljs)
### [Ansible](https://www.ansible.com)

Ansible copy files into place and update the [manifest](https://github.com/cicakhq/potato/tree/2fc12b9848237c8690e432180d275ceb8692c43c/src/template/manifest) for the [Leiningen](http://leiningen.org) file.

The major task are the Less and ClojureScript compilation, we should be able to consolidate this and reduce production chain and dependencies.

**Comment by lokedhs** [comment]
This was fixed with the new build script.
